# This is a basic workflow to help you get started with Actions

name: Anomaly Index

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master

      # Runs a set of commands using the runners shell
      - name: Calculate A-Index
        run: |
          docker run -v ${{ github.workspace }}:/${{ github.workspace }}  alexbers/anomaly python3 prototype.py /${{ github.workspace }}
